### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by goodlookingbear** [LorenzoAgnolucci/Keyframes-GAN#1]
Hello! Thank you very much for your excellent work. I was wondering if I could refer to your training code. Or do you have the training code for ASFFNet? Could you please send it to the email address xumingyuan@whu.edu.cn? Thank you very much.

**Comment by LorenzoAgnolucci** [comment]
Hi @goodlookingbear 

Thanks for your interest in our work!

I've updated the repo to provide the information on how to train our model. Please refer to the [README](https://github.com/LorenzoAgnolucci/Keyframes-GAN/tree/main?tab=readme-ov-file#training) for more details. Feel free to ask more questions if needed.

**Comment by goodlookingbear** [comment]
Hello! I'm terribly sorry to bother you again. I would like to ask about the details of the training data. For example, if I want to retrain using the Celebv-HQ dataset, should I first use a method similar to that in preprocessing.py to degrade the videos, with the degraded video frames being saved as dataroot_compressed, and dataroot_landmark being the landmarks of the degraded frames, while dataroot_reference and dataroot_gt are both the original high-resolution (HR) video frames, with each type of frames concentrated in one folder and the file names of different frames corresponding to each other? Thank you very much for your reply! Wish you a wonderful day!
